### ISSUE TITLE
etcd data stored in wrong dir?

### ISSUE THREAD

**Issue by enderson-pan** [storageos/deploy#103]
```yaml
- name: Set up persistent etcd data directory
  file:
    path:  /var/lib/{{ installation_dir }}
    state: directory
    owner: root
    group: root
    mode:  0775
```

Should be 

```yaml
- name: Set up persistent etcd data directory
  file:
    path:  {{ installation_dir }}
    state: directory
    owner: root
    group: root
    mode:  0775
```
