### ISSUE TITLE
Cannot get etcd, etcd upstream url changed

### ISSUE THREAD

**Issue by enderson-pan** [storageos/deploy#104]
```yaml
- name:  Fetch new etcd
  get_url:
    url: https://github.com/coreos/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz
    dest: /tmp/
```

Maybe:
```
- name:  Fetch new etcd
  get_url:
    url: https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz
    dest: /tmp/
```
